package org.example.services;

import org.example.models.Speaker;
import org.example.models.Tyre;
import org.example.models.Vehicle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Gives the Information about the Vehicles Generated by factory 2
 */

@Component
@Qualifier("factory2")
public class VehicleServiceFactoryTwo extends VehicleService {

    @Autowired
    public VehicleServiceFactoryTwo(TyreService tyreService, SpeakerService speakerService, InventoryStore inventoryStore) {
        super(tyreService, speakerService, inventoryStore);
        // Adjust pricing structure specific to Factory 2
    }

    @Override
    public List<Vehicle> generateVehicles(int count) {
        List<Vehicle> vehicles = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            Tyre tyre = TyreService.generateTyre();
            Speaker speaker = SpeakerService.generateSpeaker();

            // Apply pricing adjustments specific to Factory 2
            adjustPricingForFactory2(speaker);

            Vehicle vehicle = new Vehicle(tyre, speaker);
            vehicles.add(vehicle);
        }
        return vehicles;
    }

    private void adjustPricingForFactory2( Speaker speaker) {
        // Implement pricing adjustments specific to Factory 2
        // For example, you can decrease the price of the speaker by 5%
        double newSpeakerPrice = speaker.getPrice() * 0.95;
        speaker.setPrice(newSpeakerPrice);
    }
}
